#!/bin/sh
# Render monitoring config from 1Password. Produces two files:
#  - monitoring/apprise/monitoring.yaml — apprise routing, gitignored
#  - monitoring/secrets/healthchecks.env — HC_PING_URL_* env vars for the
#    service-checks and events-watcher containers, gitignored
# Called automatically by `make inject-secrets`. Idempotent.
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE="$SCRIPT_DIR/monitoring.yaml.template"
OUT="$SCRIPT_DIR/monitoring.yaml"
HC_ENV_OUT="$SCRIPT_DIR/../secrets/healthchecks.env"

TOPIC_IPTV="$(op read 'op://Personal/Ntfy/topic-iptv')" \
  || { echo "ERROR: failed to read op://Personal/Ntfy/topic-iptv" >&2; exit 1; }
TOPIC_GENERAL="$(op read 'op://Personal/Ntfy/topic-general')" \
  || { echo "ERROR: failed to read op://Personal/Ntfy/topic-general" >&2; exit 1; }

if [ -z "$TOPIC_IPTV" ] || [ -z "$TOPIC_GENERAL" ]; then
  echo "ERROR: empty topic value from 1Password" >&2
  exit 1
fi

# Discord webhooks. Stored in 1Password as full webhook URLs
# (https://discord.com/api/webhooks/<id>/<token>); we parse them into
# id/token here because Apprise's discord:// scheme takes those components
# directly rather than the raw URL.
parse_discord_webhook() {
  # Args: <op_ref> <out_id_var> <out_token_var>
  _url="$(op read "$1")" || { echo "ERROR: failed to read $1" >&2; exit 1; }
  _id="$(printf '%s' "$_url" \
    | sed -nE 's|^https://discord(app)?\.com/api/webhooks/([0-9]+)/([A-Za-z0-9_-]+).*$|\2|p')"
  _token="$(printf '%s' "$_url" \
    | sed -nE 's|^https://discord(app)?\.com/api/webhooks/([0-9]+)/([A-Za-z0-9_-]+).*$|\3|p')"
  if [ -z "$_id" ] || [ -z "$_token" ]; then
    echo "ERROR: could not parse Discord webhook URL from $1 into id/token" >&2
    echo "       expected form: https://discord.com/api/webhooks/<id>/<token>" >&2
    exit 1
  fi
  eval "$2=\$_id"
  eval "$3=\$_token"
}

parse_discord_webhook 'op://Personal/rsyduej7c4oak4uhm7v54ku7dm/alert-webhook' \
  DISCORD_IPTV_ID DISCORD_IPTV_TOKEN
parse_discord_webhook 'op://Personal/rsyduej7c4oak4uhm7v54ku7dm/infra-webhook' \
  DISCORD_INFRA_ID DISCORD_INFRA_TOKEN
parse_discord_webhook 'op://Personal/rsyduej7c4oak4uhm7v54ku7dm/cam-webhook' \
  DISCORD_CAM_ID DISCORD_CAM_TOKEN

# Healthchecks.io ping URLs. Stored in 1Password as full URLs
# (https://hc-ping.com/<uuid>); we use the full URL directly for cron-side and
# events-watcher pings, and extract just the UUID for the apprise heartbeat
# plugin which expects healthchecks://<uuid>.
HC_PING_URL_IPTV_AUTH="$(op read 'op://Personal/Healthchecks.io/ping-url-iptv-auth')"
HC_PING_URL_IPTV_CHANNEL_COUNT="$(op read 'op://Personal/Healthchecks.io/ping-url-iptv-channel-count')"
HC_PING_URL_IPTV_EPG_FRESHNESS="$(op read 'op://Personal/Healthchecks.io/ping-url-iptv-epg-freshness')"
HC_PING_URL_IPTV_CANARY_EPG="$(op read 'op://Personal/Healthchecks.io/ping-url-iptv-canary-epg')"
HC_PING_URL_IPTV_RENEWAL_WARN="$(op read 'op://Personal/Healthchecks.io/ping-url-iptv-renewal-warn')"
HC_PING_URL_EVENTS_WATCHER="$(op read 'op://Personal/Healthchecks.io/ping-url-events-watcher')"
HC_PING_URL_APPRISE_PIPELINE="$(op read 'op://Personal/Healthchecks.io/ping-url-apprise-pipeline')"

if [ -z "$HC_PING_URL_IPTV_AUTH" ] || [ -z "$HC_PING_URL_IPTV_CHANNEL_COUNT" ] \
  || [ -z "$HC_PING_URL_IPTV_EPG_FRESHNESS" ] || [ -z "$HC_PING_URL_IPTV_CANARY_EPG" ] \
  || [ -z "$HC_PING_URL_IPTV_RENEWAL_WARN" ] || [ -z "$HC_PING_URL_EVENTS_WATCHER" ] \
  || [ -z "$HC_PING_URL_APPRISE_PIPELINE" ]; then
  echo "ERROR: empty hc.io ping URL from 1Password" >&2
  exit 1
fi

HC_APPRISE_PIPELINE_UUID="$(printf '%s' "$HC_PING_URL_APPRISE_PIPELINE" \
  | sed -nE 's|^https://hc-ping\.com/([0-9a-f-]+)$|\1|p')"
if [ -z "$HC_APPRISE_PIPELINE_UUID" ]; then
  echo "ERROR: could not extract UUID from \$HC_PING_URL_APPRISE_PIPELINE" >&2
  exit 1
fi

sed \
  -e "s|{{TOPIC_IPTV}}|$TOPIC_IPTV|g" \
  -e "s|{{TOPIC_GENERAL}}|$TOPIC_GENERAL|g" \
  -e "s|{{DISCORD_IPTV_ID}}|$DISCORD_IPTV_ID|g" \
  -e "s|{{DISCORD_IPTV_TOKEN}}|$DISCORD_IPTV_TOKEN|g" \
  -e "s|{{DISCORD_INFRA_ID}}|$DISCORD_INFRA_ID|g" \
  -e "s|{{DISCORD_INFRA_TOKEN}}|$DISCORD_INFRA_TOKEN|g" \
  -e "s|{{DISCORD_CAM_ID}}|$DISCORD_CAM_ID|g" \
  -e "s|{{DISCORD_CAM_TOKEN}}|$DISCORD_CAM_TOKEN|g" \
  -e "s|{{HC_APPRISE_PIPELINE_UUID}}|$HC_APPRISE_PIPELINE_UUID|g" \
  "$TEMPLATE" > "$OUT"

# Render the healthchecks env file for service-checks + events-watcher.
# Compose loads this via env_file:; one HC_PING_URL_* per cron job plus the
# events-watcher daemon heartbeat. The apprise-pipeline URL is consumed by
# apprise itself (above), not by any container env.
mkdir -p "$(dirname "$HC_ENV_OUT")"
cat > "$HC_ENV_OUT" <<EOF
# Generated by render-config.sh from op://Personal/Healthchecks.io/*; do not edit.
HC_PING_URL_IPTV_AUTH=$HC_PING_URL_IPTV_AUTH
HC_PING_URL_IPTV_CHANNEL_COUNT=$HC_PING_URL_IPTV_CHANNEL_COUNT
HC_PING_URL_IPTV_EPG_FRESHNESS=$HC_PING_URL_IPTV_EPG_FRESHNESS
HC_PING_URL_IPTV_CANARY_EPG=$HC_PING_URL_IPTV_CANARY_EPG
HC_PING_URL_IPTV_RENEWAL_WARN=$HC_PING_URL_IPTV_RENEWAL_WARN
HC_PING_URL_EVENTS_WATCHER=$HC_PING_URL_EVENTS_WATCHER
EOF

echo "Rendered $OUT (apprise config) from template + 1Password topics"
echo "Rendered $HC_ENV_OUT (healthchecks env) from 1Password ping URLs"
