# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Daniel Snider

extends: default

rules:
  line-length: disable
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  comments-indentation: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
